blueprint:
  name: LightEase Dimmer Control
  description: "Control multiple lights with a dimmer, each using a custom curve."
  domain: automation
  input:
    control_device:
      name: Control Device
      description: "The dimmer device (Lutron, Zigbee, etc.). Select a light or sensor."
      selector:
        entity:
          domain:
            - light
            - sensor
    controlled_lights:
      name: Controlled Lights
      description: "Lights to be controlled, each with its own curve."
      selector:
        entity:
          domain: light
          multiple: true
    light_curves:
      name: Light Curves
      description: "Bézier curve for each light. Format: [[x1,y1,x2,y2], ...]"
      selector:
        object:

mode: restart

variables:
  control_value: >-
    {% if 'light.' in input.control_device %}
      {{ (state_attr(input.control_device, 'brightness') | float(default=0) / 255) * 100 }}
    {% else %}
      {{ states(input.control_device) | float(default=0) }}
    {% endif %}
  curves: "{{ input.light_curves }}"
  lights: "{{ input.controlled_lights }}"

trigger:
  - platform: state
    entity_id: !input control_device

action:
  - repeat:
      count: "{{ lights | length }}"
      sequence:
        - variables:
            light_index: "{{ repeat.index - 1 }}"
            light_entity: "{{ lights[light_index] }}"
            bezier_curve: "{{ curves[light_index] }}"
        - service: light.turn_on
          target:
            entity_id: "{{ light_entity }}"
          data:
            brightness_pct: >-
              {% set x1, y1, x2, y2 = bezier_curve %}
              {% set t = control_value / 100 %}
              {% set bezier_brightness = (3*(1-t)*(1-t)*t*y1 + 3*(1-t)*t*t*y2 + t*t*t) * 100 %}
              {{ bezier_brightness | int }}
