blueprint:
  name: Lutron Dimmer - Cubic Bezier Light Control
  description: Adjust lights using cubic Bézier curves based on Lutron dimmer input
  domain: automation
  input:
    dimmer_event:
      name: Dimmer Event
      description: ZHA event unique_id for the dimmer
      selector:
        text: {}
    input_range_low:
      name: Input Range Low
      description: Lowest input value from the dimmer (default: 2)
      default: 2
      selector:
        number:
          min: 0
          max: 255
          step: 1
          mode: box
    input_range_high:
      name: Input Range High
      description: Highest input value from the dimmer (default: 255)
      default: 255
      selector:
        number:
          min: 0
          max: 255
          step: 1
          mode: box
    bezier_curves:
      name: Bézier Curves
      description: Bézier curves for each light
      default: []
      selector:
        object: {}

mode: queued
max: 20

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      unique_id: !input dimmer_event

variables:
  t: >-
    {{
      ((trigger.event.data.params.level | float - input_range_low) /
      (input_range_high - input_range_low))
      | max(0) | min(1)
    }}
  bezier_curves: !input bezier_curves

action:
  - repeat:
      for_each: "{{ bezier_curves }}"
      sequence:
        - variables:
            p0: 0
            p3: 1
            p1x: "{{ repeat.item.bezier[0] }}"
            p1y: "{{ repeat.item.bezier[1] }}"
            p2x: "{{ repeat.item.bezier[2] }}"
            p2y: "{{ repeat.item.bezier[3] }}"
            bezier_value: >-
              {{
                ((1 - t) ** 3 * p0) +
                (3 * (1 - t) ** 2 * t * p1y) +
                (3 * (1 - t) * t ** 2 * p2y) +
                (t ** 3 * p3)
              }}
            brightness: "{{ (bezier_value * 100) | int }}"
        - service: light.turn_on
          target:
            entity_id: "{{ repeat.item.entity_id }}"
          data:
            brightness_pct: "{{ brightness }}"

  - service: logbook.log
    data:
      name: Lutron Dimmer Automation
      message: >-
        Lutron brightness {{ trigger.event.data.params.level }} → Normalized {{ t }} →
        Adjusted lights
